#!/bin/bash

if [ $# -ge 1 ]; then
  file_input=$1
fi

hateblo_path=$HOME/.local/bin/hateblo
command_pandoc="pandoc $file_input --atx-header --filter ${hateblo_path} -t markdown"

if [ $# -eq 1 ]; then
  file_output=${file_input%%opml}md
  $command_pandoc | sed 's/\\//g'
elif [ $# -eq 2 ]; then
  file_output=$2
  $command_pandoc | sed 's/\\//g' > "$file_output"
else
  echo 'Usage: opml2hateblo input.opml'
  exit 1
fi

